CUDA_VISIBLE_DEVICES=0,1,2,3 python run_ee.py \
    --model_name_or_path ./bert-base-chinese \
    --per_gpu_train_batch_size 8 \
    --per_gpu_eval_batch_size 8 \
    --gradient_accumulation_steps 2 \
    --learning_rate 5e-5 \
    --num_train_epochs 4 \
    --save_steps 500 \
    --logging_steps 500\
    --seed 48 \
    --do_eval \
    --do_train \
    --overwrite_output_dir \
    --evaluate_during_training 
